services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: trendulum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/trendulum
      SECRET_KEY: your-secret-key-here
      PYTHONUNBUFFERED: 1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug --reload
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data: